version: "3.8"
services:
  vpn:
    image: dperson/openvpn-client
    command:
      - "-a"
      - "${USERNAME};${PASSWORD}"
      - "-f"
      - "''"
    cap_add:
      - net_admin
    ports:
      - "${PROXY_PORT}:1080"
    volumes:
      - "${VPN_CONFIG}:/vpn/vpn.conf:ro"
      - "/dev/net:/dev/net:z"

  proxy:
    image: serjs/go-socks5-proxy
    network_mode: "service:vpn"
    depends_on:
      - vpn
